# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='accepted_problem_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='submission_number',
        ),
    ]
