# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-28 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20170124_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='problems_status',
        ),
        migrations.AddField(
            model_name='profile',
            name='submit_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='token',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
