# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-07 15:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '0006_problem_test_case_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('submission_id', models.AutoField(primary_key=True, serialize=False, verbose_name='SID')),
                ('language', models.IntegerField()),
                ('code', models.TextField()),
                ('shared', models.BooleanField(default=False)),
                ('status', models.CharField(default='waiting', max_length=20)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('memory', models.IntegerField(blank=True, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('ac_info', models.TextField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('judge_start_time', models.DateTimeField(blank=True, null=True)),
                ('judge_end_time', models.DateTimeField(blank=True, null=True)),
                ('v_run_id', models.CharField(blank=True, max_length=100, null=True)),
                ('v_length', models.CharField(blank=True, max_length=20, null=True)),
                ('v_user', models.CharField(blank=True, max_length=50, null=True)),
                ('v_submit_time', models.CharField(blank=True, max_length=50, null=True)),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='problem.Problem')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
