# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-28 17:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '0005_problem_last_update_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('submission_id', models.AutoField(primary_key=True, serialize=False, verbose_name='SID')),
                ('language', models.IntegerField(choices=[(b'c', 1), (b'java', 3), (b'python3', 5), (b'c++', 2), (b'python2', 4)])),
                ('code', models.TextField()),
                ('shared', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(b'presentation_error', 5), (b'time_limit_exceeded', 2), (b'unknown_error', 10), (b'wrong_answer', 6), (b'compile_error', 4), (b'accepted', 0), (b'submit_error', 9), (b'system_error', 7), (b'memory_limit_exceeded', 3), (b'waiting', 8), (b'runtime_error', 1)], default=8)),
                ('time', models.IntegerField()),
                ('memory', models.IntegerField()),
                ('info', models.TextField(blank=True, null=True)),
                ('ac_info', models.TextField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('judge_start_time', models.DateTimeField(blank=True, null=True)),
                ('judge_end_time', models.DateTimeField(blank=True, null=True)),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='problem.Problem')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
