# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-15 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='v_language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='v_length',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='v_memory',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='v_run_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='v_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='v_submit_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='v_time',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='v_user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.IntegerField(choices=[(1, b'c'), (2, b'c++'), (3, b'java'), (4, b'python2'), (5, b'python3')]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='memory',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.IntegerField(choices=[(0, b'accepted'), (1, b'runtime error'), (2, b'time limit exceeded'), (3, b'memory limit exceeded'), (4, b'compile error'), (5, b'presentation error'), (6, b'wrong answer'), (7, b'system error'), (8, b'waiting'), (9, b'submit error'), (10, b'unknown error')], default=8),
        ),
        migrations.AlterField(
            model_name='submission',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
