# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-09 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_auto_20170307_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Submit Time'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Run ID'),
        ),
    ]
