# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-06 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0004_remove_submission_v_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(default='waiting', max_length=50),
        ),
    ]
