# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-06 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0005_auto_20170406_2000'),
    ]

    operations = [
    ]
