# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-09 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.IntegerField()),
                ('virtual_judge', models.BooleanField()),
                ('time_limit', models.IntegerField()),
                ('memory_limit', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'judge_queue',
            },
        ),
        migrations.CreateModel(
            name='Judger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ip_address', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
                ('max_judge_number', models.IntegerField(default=1)),
                ('use_judge_number', models.IntegerField(default=0)),
                ('free', models.BooleanField(default=True)),
                ('token', models.CharField(max_length=65)),
                ('status', models.CharField(max_length=31)),
                ('active', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'judger',
            },
        ),
    ]
