# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-12 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judgequeue',
            name='virtual_judge',
        ),
        migrations.RemoveField(
            model_name='judger',
            name='free',
        ),
        migrations.AddField(
            model_name='judgequeue',
            name='language_name',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='judgequeue',
            name='oj',
            field=models.SmallIntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='judgequeue',
            name='problem_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='judgequeue',
            name='spj_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='judgequeue',
            name='src_code',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='judgequeue',
            name='test_case_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='judgequeue',
            name='memory_limit',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='judgequeue',
            name='time_limit',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='judger',
            name='status',
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
    ]
