# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-06 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judger', '0002_auto_20170312_1355'),
    ]

    operations = [
    ]
