# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('problem_id', models.AutoField(primary_key=True, serialize=False)),
                ('virtual_id', models.CharField(max_length=50)),
                ('oj_name', models.CharField(choices=[('POJ', 'POJ'), ('HDU', 'HDU'), ('Codeforces', 'Codeforces'), ('USTBOJ', 'USTBOJ')], max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('time_limit', models.IntegerField()),
                ('memory_limit', models.IntegerField()),
                ('os', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=30000)),
                ('input_description', models.TextField(max_length=10000)),
                ('output_description', models.TextField(max_length=10000)),
                ('hint', models.CharField(blank=True, default='', max_length=256)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('short_name', models.CharField(max_length=10)),
                ('intro', models.TextField(default='')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(blank=True, to='problem.ProblemTag'),
        ),
    ]
