# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='input_sample',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='problem',
            name='output_sample',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.TextField(default='', max_length=30000),
        ),
        migrations.AlterField(
            model_name='problem',
            name='input_description',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='problem',
            name='output_description',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
