# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_auto_20170124_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='remote_accepted_user_number',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='problem',
            name='remote_submission_user_number',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='problem',
            name='memory_limit',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='problem',
            name='oj_name',
            field=models.CharField(choices=[('POJ', 'POJ'), ('HDU', 'HDU'), ('Codeforces', 'Codeforces'), ('USTBOJ', 'USTBOJ')], max_length=50, verbose_name='OJ'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='PID'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='time_limit',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='virtual_id',
            field=models.CharField(max_length=50, verbose_name='VID'),
        ),
    ]
