# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_auto_20170125_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='hint',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='problem',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Source'),
        ),
    ]
