# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0004_auto_20170125_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='last_update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
