# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-15 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0005_problem_last_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='test_case_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
