# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-06 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0006_problem_test_case_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='test_case_dir_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
