# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-06 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0008_auto_20170506_2256'),
    ]

    operations = [
    ]
